### ISSUE TITLE
Wrong formula for the mean number of test with bisection strategy

### ISSUE THREAD

**Issue by ghost** [EFavDB/pooling#1]
Hi, I've been working on the same problem recently, and I just want to let you know that your formula is only partially correct. Though you did try to average the number of test, but you didn't take into account that you only do a test (a node in the tree) when there's a path from the root node to that node. Hence, you overestimate the number of test needed.

To see this, consider p=0.5 and k=2, I get 5.6875 but you get 5.875, which is an overestimation.

The correct way to calculate the mean number of test in this situation should be 

$$
1+2(1(1-0.5^4)+2(1-0.5^2)(1-0.5^4)),
$$
which gives 5.6875. If you use your formula for calculation, you have ignored that (1-0.5^4) factor. This together with the (1-0.5^2) factor says that you only do level 2 test when there's a path from the root node to a level 2 node, or, equivalently, you must test positive at level 0 and level 1. I hope this is clear enough, and please let me know what you think of my suggestion. Thanks!

**Comment by jonathanlandy** [comment]
Hi, Zhaoziyuan.  Thanks for you comment.  If you look in my notebook, I have written some code to check the result at the end.  For the example you give of K=2 and p=0.5, I get 5.87518 +/- 0.003, when running on one million examples.  This is consistent with the formula I gave.  Perhaps you are working on a slightly different variant of the pooling strategy and that is why our answers do not agree.

**Comment by ghost** [comment]
Thank you for your reply! I checked your code and also tried to enumerate through all the cases and calculate the mean value combinatorially. I think you are correct after all, and I'm indeed using a slightly different assumption. In comparison your model is simpler to derive and that's neat!
